---
# LokiStack Instance for Redis Enterprise Logging
# Size: 1x.demo - Suitable for POC/demo environments
# Storage: Object storage via ODF/Ceph S3 (NooBaa)
#
# This creates a complete Loki deployment with:
# - Ingester: Receives and processes logs
# - Distributor: Routes logs to ingesters
# - Querier: Handles log queries
# - Query Frontend: Query optimization
# - Compactor: Log compaction and retention
# - Index Gateway: Index management

apiVersion: loki.grafana.com/v1
kind: LokiStack
metadata:
  name: logging-loki
  namespace: openshift-logging
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  # Size: 1x.demo
  # - Single replica per component
  # - Minimal resource requirements
  # - Suitable for POC/demo/dev environments
  size: 1x.demo
  
  # Storage configuration
  storage:
    # Schema version v13 (latest stable)
    schemas:
    - version: v13
      effectiveDate: "2024-01-01"

    # Object storage secret
    # Points to ODF/Ceph S3 (NooBaa) or external S3
    secret:
      name: logging-loki-s3
      type: s3

    # TLS configuration for S3 (NooBaa)
    # Use service-ca.crt to trust OpenShift service certificates
    tls:
      caKey: service-ca.crt

  # Storage class for PVCs
  # Uses ODF Ceph RBD for persistent storage (external mode)
  storageClassName: ocs-external-storagecluster-ceph-rbd
  
  # Tenant mode: openshift-logging
  # Integrates with OpenShift logging infrastructure
  tenants:
    mode: openshift-logging
  
  # Resource limits (optional - can be customized)
  limits:
    global:
      # Log retention period
      retention:
        days: 7
      
      # Query limits
      queries:
        maxEntriesLimitPerQuery: 5000
        maxChunksPerQuery: 2000000
  
  # Template for component customization (optional)
  template:
    compactor:
      replicas: 1
    distributor:
      replicas: 1
    gateway:
      replicas: 1
    indexGateway:
      replicas: 1
    ingester:
      replicas: 1
    querier:
      replicas: 1
    queryFrontend:
      replicas: 1

---
# ObjectBucketClaim for Loki Storage
# This creates an S3 bucket automatically using ODF/Ceph
# No manual bucket creation needed!

apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: loki-logs-bucket
  namespace: openshift-logging
  annotations:
    argocd.argoproj.io/sync-wave: "8"
spec:
  # Bucket name
  bucketName: loki-logs

  # Storage class for object storage
  # ODF provides 'openshift-storage.noobaa.io' for S3-compatible storage
  storageClassName: openshift-storage.noobaa.io

  # Additional config (optional)
  additionalConfig:
    bucketclass: noobaa-default-bucket-class

---
# Note: The logging-loki-s3 secret is created automatically by the loki-secret-sync-job.yaml
# The Job copies credentials from the ObjectBucketClaim secret to the LokiStack secret
# See: loki-secret-sync-job.yaml (sync-wave 10)

