---
# ServiceAccount for Secret Sync Job
apiVersion: v1
kind: ServiceAccount
metadata:
  name: loki-secret-sync
  namespace: openshift-logging
  annotations:
    argocd.argoproj.io/sync-wave: "9"

---
# Role: Allow reading OBC secret/configmap and updating Loki secret
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: loki-secret-sync
  namespace: openshift-logging
  annotations:
    argocd.argoproj.io/sync-wave: "9"
rules:
- apiGroups: [""]
  resources: ["secrets", "configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]

---
# RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: loki-secret-sync
  namespace: openshift-logging
  annotations:
    argocd.argoproj.io/sync-wave: "9"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: loki-secret-sync
subjects:
- kind: ServiceAccount
  name: loki-secret-sync
  namespace: openshift-logging

---
# Job: Sync OBC credentials to Loki secret
# This job runs once to copy credentials from the auto-generated OBC secret
# to the logging-loki-s3 secret that LokiStack expects

apiVersion: batch/v1
kind: Job
metadata:
  name: loki-secret-sync
  namespace: openshift-logging
  annotations:
    argocd.argoproj.io/sync-wave: "10"
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  backoffLimit: 3
  ttlSecondsAfterFinished: 600
  template:
    metadata:
      labels:
        app: loki-secret-sync
    spec:
      serviceAccountName: loki-secret-sync
      restartPolicy: OnFailure
      containers:
      - name: sync
        image: quay.io/openshift/origin-cli:latest
        command:
        - /bin/bash
        - -c
        - |
          set -e
          
          echo "=========================================="
          echo "Loki S3 Secret Sync Job"
          echo "=========================================="
          echo ""
          
          # Wait for OBC to be ready
          echo "⏳ Waiting for ObjectBucketClaim to be ready..."
          for i in {1..30}; do
            if oc get secret loki-logs-bucket -n openshift-logging &>/dev/null; then
              echo "✅ OBC secret found"
              break
            fi
            echo "   Attempt $i/30: Waiting for OBC secret..."
            sleep 10
          done
          
          # Get credentials from OBC secret
          echo ""
          echo "🔑 Reading OBC credentials..."
          ACCESS_KEY=$(oc get secret loki-logs-bucket -n openshift-logging -o jsonpath='{.data.AWS_ACCESS_KEY_ID}' | base64 -d)
          SECRET_KEY=$(oc get secret loki-logs-bucket -n openshift-logging -o jsonpath='{.data.AWS_SECRET_ACCESS_KEY}' | base64 -d)
          
          # Get endpoint from OBC configmap
          echo "📍 Reading OBC endpoint..."
          BUCKET_HOST=$(oc get configmap loki-logs-bucket -n openshift-logging -o jsonpath='{.data.BUCKET_HOST}')
          BUCKET_NAME=$(oc get configmap loki-logs-bucket -n openshift-logging -o jsonpath='{.data.BUCKET_NAME}')
          
          # Construct S3 endpoint URL
          ENDPOINT="https://${BUCKET_HOST}"
          
          echo "   Endpoint: $ENDPOINT"
          echo "   Bucket: $BUCKET_NAME"
          echo "   Access Key: ${ACCESS_KEY:0:10}..."
          
          # Create/Update logging-loki-s3 secret
          echo ""
          echo "🔐 Creating/Updating logging-loki-s3 secret..."
          
          oc create secret generic logging-loki-s3 \
            --from-literal=endpoint="$ENDPOINT" \
            --from-literal=bucketnames="$BUCKET_NAME" \
            --from-literal=region="us-east-1" \
            --from-literal=access_key_id="$ACCESS_KEY" \
            --from-literal=access_key_secret="$SECRET_KEY" \
            --namespace=openshift-logging \
            --dry-run=client -o yaml | oc apply -f -
          
          echo "✅ Secret synced successfully!"
          echo ""
          echo "=========================================="
          echo "✅ Loki S3 Secret Sync Complete"
          echo "=========================================="

