apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-cluster-demo
  namespace: openshift-gitops
  labels:
    cluster: demo
    component: infrastructure
    type: redis-cluster
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform-team
  
  source:
    repoURL: https://github.com/alan-teodoro/poc-gitops.git
    targetRevision: main
    path: helm-charts/redis-enterprise-cluster
    helm:
      valueFiles:
        - ../../clusters/redis-cluster-demo/cluster.yaml
  
  destination:
    server: https://kubernetes.default.svc
    namespace: redis-enterprise
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - RespectIgnoreDifferences=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  
  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      jsonPointers:
        - /spec/volumeClaimTemplates

