---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: redis-demo
  namespace: openshift-gitops
  labels:
    project: redis-demo
    managed-by: platform-team
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: |
    AppProject for Redis Demo - Multi-tenant setup.
    Demonstrates shared Redis Enterprise cluster serving multiple teams.
    Provides namespace isolation and resource type restrictions.
  
  # Source repositories allowed for this project
  sourceRepos:
    - '*'  # Allow all repos (can be restricted to specific org/repo)
  
  # Destination clusters and namespaces
  destinations:
    # Allow deployment to Redis Enterprise cluster namespace
    - namespace: 'redis-enterprise'
      server: 'https://kubernetes.default.svc'
    # Allow deployment to team1 database namespaces
    - namespace: 'redis-team1-dev'
      server: 'https://kubernetes.default.svc'
    - namespace: 'redis-team1-prod'
      server: 'https://kubernetes.default.svc'
    # Allow deployment to team2 database namespaces
    - namespace: 'redis-team2-dev'
      server: 'https://kubernetes.default.svc'
    - namespace: 'redis-team2-prod'
      server: 'https://kubernetes.default.svc'
  
  # Cluster-scoped resources allowed (very restrictive)
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
  
  # Namespace-scoped resources allowed
  namespaceResourceWhitelist:
    # Redis Enterprise resources
    - group: 'app.redislabs.com'
      kind: RedisEnterpriseCluster
    - group: 'app.redislabs.com'
      kind: RedisEnterpriseDatabase
    
    # OpenShift/Kubernetes core resources
    - group: 'route.openshift.io'
      kind: Route
    - group: ''
      kind: Service
    - group: ''
      kind: Secret
    - group: ''
      kind: ConfigMap
    - group: ''
      kind: ServiceAccount
    - group: ''
      kind: PersistentVolumeClaim
    
    # RBAC resources
    - group: 'rbac.authorization.k8s.io'
      kind: Role
    - group: 'rbac.authorization.k8s.io'
      kind: RoleBinding
    
    # External Secrets
    - group: 'external-secrets.io'
      kind: ExternalSecret
    - group: 'external-secrets.io'
      kind: SecretStore
  
  # Resources explicitly denied (platform-managed only)
  namespaceResourceBlacklist:
    - group: ''
      kind: ResourceQuota
    - group: ''
      kind: LimitRange
    - group: 'templates.gatekeeper.sh'
      kind: ConstraintTemplate
    - group: 'constraints.gatekeeper.sh'
      kind: '*'
  
  # RBAC roles for this project
  roles:
    # Admin role - full control over demo resources
    - name: admin
      description: Admin privileges for Redis Demo
      policies:
        - p, proj:redis-demo:admin, applications, *, redis-demo/*, allow
        - p, proj:redis-demo:admin, repositories, *, *, allow
      groups:
        - platform-admins

    # Team1 role - can manage team1 resources
    - name: team1
      description: Team 1 privileges
      policies:
        - p, proj:redis-demo:team1, applications, get, redis-demo/*team1*, allow
        - p, proj:redis-demo:team1, applications, sync, redis-demo/*team1*, allow
        - p, proj:redis-demo:team1, logs, get, redis-demo/*team1*, allow
      groups:
        - team1-developers

    # Team2 role - can manage team2 resources
    - name: team2
      description: Team 2 privileges
      policies:
        - p, proj:redis-demo:team2, applications, get, redis-demo/*team2*, allow
        - p, proj:redis-demo:team2, applications, sync, redis-demo/*team2*, allow
        - p, proj:redis-demo:team2, logs, get, redis-demo/*team2*, allow
      groups:
        - team2-developers

    # Read-only role - view only
    - name: readonly
      description: Read-only access for Redis Demo
      policies:
        - p, proj:redis-demo:readonly, applications, get, redis-demo/*, allow
        - p, proj:redis-demo:readonly, logs, get, redis-demo/*, allow
      groups:
        - redis-demo-viewers
  
  # Sync windows (optional - can restrict when syncs can happen)
  # syncWindows:
  #   - kind: allow
  #     schedule: '0 9-17 * * 1-5'  # Mon-Fri 9am-5pm
  #     duration: 8h
  #     applications:
  #       - '*-prod'
  #     manualSync: true
  
  # Orphaned resources monitoring
  orphanedResources:
    warn: true

