apiVersion: app.redislabs.com/v1
kind: RedisEnterpriseCluster
metadata:
  name: {{ .Values.redis.clusterName }}
  namespace: {{ .Values.namespace }}
  labels:
    cluster: {{ .Values.cluster.name }}
    team: {{ .Values.cluster.team }}
    datacenter: {{ .Values.cluster.datacenter }}
    {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  annotations:
    # Prevent accidental deletion by ArgoCD
    argocd.argoproj.io/sync-options: "Prune=false"
    {{- with .Values.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  nodes: {{ .Values.redis.nodes }}
  
  redisEnterpriseNodeResources:
    requests:
      cpu: {{ .Values.redis.resources.requests.cpu | quote }}
      memory: {{ .Values.redis.resources.requests.memory | quote }}
    limits:
      cpu: {{ .Values.redis.resources.limits.cpu | quote }}
      memory: {{ .Values.redis.resources.limits.memory | quote }}
  
  {{- if .Values.redis.persistence.enabled }}
  # Persistent storage configuration
  persistentSpec:
    enabled: true
    storageClassName: {{ .Values.redis.persistence.storageClassName }}
    volumeSize: {{ .Values.redis.persistence.volumeSize }}
  {{- end }}
  
  redisEnterpriseImageSpec:
    imagePullPolicy: IfNotPresent
    versionTag: {{ .Values.redis.version | quote }}

  {{- if .Values.redis.podAntiAffinity }}
  # Pod anti-affinity rules for high availability
  podAntiAffinity:
    {{- toYaml .Values.redis.podAntiAffinity | nindent 4 }}
  {{- end }}

  {{- if .Values.logging.sidecar.enabled }}
  # Grafana Alloy sidecar for internal logs collection
  sideContainersSpec:
    - name: alloy
      image: {{ .Values.logging.sidecar.image }}
      args:
        - run
        - --server.http.listen-addr=0.0.0.0:12345
        - --storage.path=/tmp/alloy
        - /etc/alloy/config.alloy
      env:
        - name: CLUSTER_NAME
          value: {{ .Values.redis.clusterName | quote }}
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
      volumeMounts:
        - name: redis-enterprise-storage
          mountPath: /var/opt/redislabs/log
          subPath: logs
          readOnly: true
        - name: alloy-config
          mountPath: /etc/alloy
      resources:
        requests:
          cpu: {{ .Values.logging.sidecar.resources.requests.cpu | quote }}
          memory: {{ .Values.logging.sidecar.resources.requests.memory | quote }}
        limits:
          cpu: {{ .Values.logging.sidecar.resources.limits.cpu | quote }}
          memory: {{ .Values.logging.sidecar.resources.limits.memory | quote }}
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
  {{- end }}
