---
# Allow Kubernetes API Network Policy
# Purpose: Allow Redis Enterprise Operator to communicate with Kubernetes API
# Required for: Operator functionality, resource management
# Ports: 443 (HTTPS), 6443 (K8s API)
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-k8s-api
  namespace: redis-enterprise
  labels:
    app: redis-enterprise
    component: network-policy
    security: k8s-api
spec:
  # Apply to all pods in namespace
  podSelector: {}
  
  policyTypes:
    - Egress
  
  egress:
    # Allow access to Kubernetes API server
    # Note: API server is typically in default namespace or master nodes
    - to:
        # Allow to default namespace (kubernetes service)
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: default
      ports:
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 6443
    
    # Allow to master nodes (OpenShift API server)
    - to:
        # Allow to any IP (API server may be outside cluster)
        - podSelector: {}
      ports:
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 6443

