---
# Allow Redis Internode Communication Network Policy
# Purpose: Allow Redis Enterprise cluster nodes to communicate with each other
# Required for: Cluster formation, replication, failover
# Ports: Multiple (see below)
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-redis-internode
  namespace: redis-enterprise
  labels:
    app: redis-enterprise
    component: network-policy
    security: internode
spec:
  # Apply to Redis Enterprise pods
  podSelector:
    matchLabels:
      app: redis-enterprise
  
  policyTypes:
    - Ingress
    - Egress
  
  ingress:
    # Allow from other Redis Enterprise pods in same namespace
    # Based on official Redis Enterprise port documentation:
    # https://redis.io/docs/latest/operate/rs/networking/port-configurations/
    - from:
        - podSelector:
            matchLabels:
              app: redis-enterprise
      ports:
        # Internode communication (3333-3354)
        - protocol: TCP
          port: 3333
        - protocol: TCP
          port: 3334
        - protocol: TCP
          port: 3335
        - protocol: TCP
          port: 3336
        - protocol: TCP
          port: 3337
        - protocol: TCP
          port: 3338
        - protocol: TCP
          port: 3339
        - protocol: TCP
          port: 3340
        - protocol: TCP
          port: 3341
        - protocol: TCP
          port: 3342
        - protocol: TCP
          port: 3343
        - protocol: TCP
          port: 3344
        - protocol: TCP
          port: 3345
        - protocol: TCP
          port: 3350
        - protocol: TCP
          port: 3351
        - protocol: TCP
          port: 3352
        - protocol: TCP
          port: 3353
        - protocol: TCP
          port: 3354

        # Sentinel port
        - protocol: TCP
          port: 36379

        # Proxy traffic
        - protocol: TCP
          port: 1968

        # Discovery Service
        - protocol: TCP
          port: 8001

        # Metrics endpoint (Prometheus)
        - protocol: TCP
          port: 8070

        # Internal metrics ports
        - protocol: TCP
          port: 3347
        - protocol: TCP
          port: 3348
        - protocol: TCP
          port: 3349
        - protocol: TCP
          port: 8000
        - protocol: TCP
          port: 8071
        - protocol: TCP
          port: 9091
        - protocol: TCP
          port: 9125

        # Management UI (HTTPS)
        - protocol: TCP
          port: 8443

        # REST API ports
        - protocol: TCP
          port: 9443
        - protocol: TCP
          port: 8080
        - protocol: TCP
          port: 3346

        # CRDB coordinator (Active-Active)
        - protocol: TCP
          port: 9081

        # Cluster API internal
        - protocol: TCP
          port: 9082

        # Envoy health monitoring
        - protocol: TCP
          port: 8002
        - protocol: TCP
          port: 8004
        - protocol: TCP
          port: 8006

        # Web proxy to cnm_http/cm
        - protocol: TCP
          port: 8444
        - protocol: TCP
          port: 9080

        # Authentication service
        - protocol: TCP
          port: 3355

        # Zabbix monitoring
        - protocol: TCP
          port: 10050

  egress:
    # Allow to other Redis Enterprise pods in same namespace
    # Using same ports as ingress for bidirectional communication
    - to:
        - podSelector:
            matchLabels:
              app: redis-enterprise
      # Allow ALL ports for egress to simplify configuration
      # This is safe because we're only allowing to pods with app=redis-enterprise label
      #
      # Note: This also covers:
      # - Database ports: 10000-19999 (configurable range)
      # - Database shard traffic: 20000-29999 (CRITICAL for cluster operation)
      #
      # Listing all 20,000 ports individually would make this file unmanageable,
      # so we allow all egress to Redis Enterprise pods.

