{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.database.name }}-{{ .Values.database.env }}
  namespace: {{ .Values.cluster.namespace | default (printf "redis-%s" .Values.cluster.name) }}
  labels:
    cluster: {{ .Values.cluster.name }}
    team: {{ .Values.cluster.team }}
    database: {{ .Values.database.name }}
    env: {{ .Values.database.env }}
    component: database
    {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  to:
    kind: Service
    name: redis-{{ .Values.redis.databasePort }}
  port:
    targetPort: {{ .Values.redis.databasePort }}
  tls:
    termination: {{ .Values.route.tlsTermination }}
    insecureEdgeTerminationPolicy: Redirect
{{- end }}

