---
# Gatekeeper Operator Subscription
# Purpose: Install Gatekeeper for policy enforcement
# Managed by: Platform Team

apiVersion: v1
kind: Namespace
metadata:
  name: openshift-gatekeeper-system
  labels:
    openshift.io/cluster-monitoring: "true"
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted

---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: gatekeeper-operator
  namespace: openshift-gatekeeper-system
spec:
  upgradeStrategy: Default

---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: gatekeeper-operator-product
  namespace: openshift-gatekeeper-system
spec:
  channel: stable
  installPlanApproval: Automatic
  name: gatekeeper-operator-product
  source: redhat-operators
  sourceNamespace: openshift-marketplace

---
# Gatekeeper Instance
# This creates the actual Gatekeeper deployment
apiVersion: operator.gatekeeper.sh/v1alpha1
kind: Gatekeeper
metadata:
  name: gatekeeper
  namespace: openshift-gatekeeper-system
spec:
  audit:
    replicas: 1
    logLevel: INFO
    auditInterval: 60s
    constraintViolationLimit: 20
    auditFromCache: Automatic
    auditChunkSize: 500
    emitAuditEvents: Enabled
    resources:
      limits:
        cpu: 1000m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 256Mi
  
  validatingWebhook: Enabled
  mutatingWebhook: Disabled
  
  webhook:
    replicas: 2
    logLevel: INFO
    emitAdmissionEvents: Enabled
    failurePolicy: Ignore
    resources:
      limits:
        cpu: 1000m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 256Mi
  
  image:
    imagePullPolicy: IfNotPresent
  
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: gatekeeper.sh/operation
              operator: In
              values:
              - webhook
          topologyKey: kubernetes.io/hostname

