---
# Gatekeeper Instance
# Purpose: Creates the actual Gatekeeper deployment and CRDs
# Managed by: Platform Team
# Note: Requires Gatekeeper Operator to be installed first

apiVersion: operator.gatekeeper.sh/v1alpha1
kind: Gatekeeper
metadata:
  name: gatekeeper
spec:
  # Audit configuration
  audit:
    replicas: 1
    logLevel: INFO
    auditInterval: 60s
    constraintViolationLimit: 20
    auditFromCache: Automatic
    auditChunkSize: 500
    emitAuditEvents: Enabled
    resources:
      limits:
        cpu: 1000m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 256Mi
  
  # Webhook configuration
  validatingWebhook: Enabled
  mutatingWebhook: Disabled
  
  webhook:
    replicas: 2
    logLevel: INFO
    emitAdmissionEvents: Enabled
    failurePolicy: Ignore
    resources:
      limits:
        cpu: 1000m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 256Mi
  
  # Image configuration
  image:
    imagePullPolicy: IfNotPresent
  
  # Pod anti-affinity for HA
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: gatekeeper.sh/operation
              operator: In
              values:
              - webhook
          topologyKey: kubernetes.io/hostname

# ========================================
# How to Apply
# ========================================
# oc apply -f platform/operators/gatekeeper-instance.yaml
#
# Wait for pods:
#   watch oc get pods -n openshift-gatekeeper-system
#
# Verify CRDs:
#   oc get crd | grep constrainttemplate

