# Example: High-Performance Cache Database
#
# Use Case: Application cache for frequently accessed data
# 
# Features:
# - No persistence (in-memory only for maximum performance)
# - LRU eviction to automatically remove least recently used items
# - Replication enabled for high availability
# - No TLS (suitable for dev/test, enable for production)
#
# Best For:
# - API response caching
# - Session caching
# - Temporary data storage
# - Read-heavy workloads

apiVersion: app.redislabs.com/v1
kind: RedisEnterpriseDatabase
metadata:
  name: app-cache
  namespace: orders-redis-dev
  labels:
    app.kubernetes.io/name: redis-database
    app.kubernetes.io/component: cache
    use-case: cache
spec:
  # Memory allocation - adjust based on cache size needs
  memorySize: 2GB
  
  # Enable replication for high availability
  # Creates a replica shard for failover
  replication: true
  
  # No persistence - cache data is ephemeral
  # Restart will clear all data
  persistence: disabled
  
  # Database port - must be unique per cluster
  databasePort: 12000
  
  # TLS disabled for development
  # For production, set to 'enabled'
  tlsMode: disabled
  
  # Database type
  type: redis
  
  # Eviction policy: Remove least recently used items when memory is full
  # This is ideal for cache use cases
  evictionPolicy: volatile-lru
  
  # Optional: Proxy policy for connection handling
  # proxyPolicy: single
  
  # Optional: Shard count for larger caches
  # shardCount: 2

# Usage Example:
# ---------------
# After deployment, connect and use as cache:
#
# redis-cli -h app-cache -p 12000
#
# # Set cache entry with TTL
# SET user:1001 '{"name":"John","email":"john@example.com"}' EX 3600
#
# # Get cache entry
# GET user:1001
#
# # Check TTL
# TTL user:1001
#
# # Set without TTL (will be evicted by LRU when memory is full)
# SET session:abc123 '{"user_id":1001,"login_time":"2024-01-01T10:00:00Z"}'

