# Example: Sharded Database for High Throughput
#
# Use Case: Large datasets requiring high throughput and scalability
#
# Features:
# - Multiple shards for distributed data
# - Higher throughput than single-shard databases
# - Automatic data distribution across shards
# - Replication for high availability
#
# Best For:
# - Large datasets (> 25GB)
# - High-traffic applications
# - Scalable workloads
# - Applications requiring high ops/sec

apiVersion: app.redislabs.com/v1
kind: RedisEnterpriseDatabase
metadata:
  name: sharded-data
  namespace: orders-redis-dev
  labels:
    app.kubernetes.io/name: redis-database
    app.kubernetes.io/component: datastore
    use-case: sharded
spec:
  # Total memory allocation across all shards
  # With 4 shards, each shard gets ~2GB
  memorySize: 8GB
  
  # Enable replication
  # Each shard will have a replica
  replication: true
  
  # Persistence configuration
  persistence: aofEverySecond
  
  # Database port
  databasePort: 12200
  
  # TLS configuration
  tlsMode: disabled
  
  # Database type
  type: redis
  
  # Eviction policy
  evictionPolicy: volatile-lru
  
  # Number of shards
  # More shards = higher throughput and better distribution
  # Recommended: 1 shard per 10-25GB of data
  # Each shard can handle ~25K ops/sec
  shardCount: 4
  
  # Proxy policy: How clients connect to shards
  # Options:
  #   - single: Single endpoint, proxy routes to shards (default)
  #   - all-master-shards: Expose all master shards
  #   - all-nodes: Expose all nodes (masters and replicas)
  proxyPolicy: single

# Sharding Behavior:
# ------------------
# - Data is automatically distributed across shards using hash slots
# - Redis uses CRC16 hash of the key to determine shard
# - Keys with hash tags {} are placed on the same shard
#   Example: {user:1001}:profile and {user:1001}:settings
#            will be on the same shard
#
# - Multi-key operations work only if keys are on the same shard
# - Use hash tags to ensure related keys are co-located

# Usage Example:
# ---------------
# redis-cli -h sharded-data -p 12200
#
# # Regular keys - distributed across shards
# SET user:1001 "data1"
# SET user:1002 "data2"
# SET user:1003 "data3"
#
# # Hash tags - ensure keys are on same shard
# SET {user:1001}:profile "profile_data"
# SET {user:1001}:settings "settings_data"
# SET {user:1001}:preferences "preferences_data"
#
# # Multi-key operations on same shard work
# MGET {user:1001}:profile {user:1001}:settings
#
# # Check cluster info
# INFO CLUSTER

# Performance Characteristics:
# ----------------------------
# Shard Count | Approx Throughput | Use Case
# ------------|-------------------|----------
# 1           | ~25K ops/sec      | Small datasets, simple workloads
# 2           | ~50K ops/sec      | Medium datasets, moderate traffic
# 4           | ~100K ops/sec     | Large datasets, high traffic
# 8           | ~200K ops/sec     | Very large datasets, very high traffic
# 16          | ~400K ops/sec     | Massive datasets, extreme traffic

# Considerations:
# ---------------
# - More shards = higher throughput but more complexity
# - Multi-key operations require keys on same shard (use hash tags)
# - Resharding is possible but requires planning
# - Monitor shard distribution to avoid hotspots
# - Each shard consumes cluster resources

