# Session Store Database - Development Environment

database:
  name: session-store
  env: dev
  type: session

cluster:
  name: orders
  team: orders
  costCenter: CC-1234
  datacenter: dc1

namespace: redis-orders-dev

redis:
  clusterName: orders-redis-cluster
  memorySize: 512MB
  replication: false
  persistence: disabled
  databasePort: 12001
  tlsMode: enabled
  evictionPolicy: volatile-ttl
  shardCount: 1
  type: redis

route:
  enabled: true
  tlsTermination: passthrough

labels:
  app: orders-api
  app.kubernetes.io/managed-by: argocd
  gitops: argocd
  component: session

annotations:
  description: "Session store database for Orders application - Development"

