# Session Store Database - Production Environment

database:
  name: session-store
  env: prod
  type: session

cluster:
  name: orders
  team: orders-team
  datacenter: dc1

namespace: redis-orders

redis:
  clusterName: orders-redis-cluster
  memorySize: 2GB
  replication: true
  persistence: aofEverySecond
  databasePort: 12001
  tlsMode: enabled
  evictionPolicy: volatile-ttl
  shardCount: 2
  type: redis

route:
  enabled: true
  tlsTermination: passthrough

labels:
  app.kubernetes.io/managed-by: argocd
  gitops: argocd
  app: orders
  component: session
  env: prod

annotations:
  description: "Session store database for Orders application - Production"

