# Session Store Database - Production Environment

database:
  name: session-store
  env: prod
  type: session

cluster:
  name: orders
  team: orders
  costCenter: CC-1234
  datacenter: dc1

namespace: redis-orders-prod

redis:
  clusterName: orders-redis-cluster
  memorySize: 512MB
  replication: false
  persistence: aofEverySecond
  databasePort: 12003
  tlsMode: enabled
  evictionPolicy: volatile-ttl
  shardCount: 1
  type: redis

route:
  enabled: true
  tlsTermination: passthrough

labels:
  app: orders-api
  app.kubernetes.io/managed-by: argocd
  gitops: argocd
  component: session
  env: prod

annotations:
  description: "Session store database for Orders application - Production"

