{
 "title": "Cluster Status Dashboard",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(redis_server_up,cluster)"
    }
   },
   {
    "name": "aggregation",
    "label": "aggregation interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "db",
    "label": "db",
    "query": {
     "query": "label_values(endpoint_client_connections{cluster=\"$cluster\"},db)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Database Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(redis_server_up{cluster=\"$cluster\"})",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(redis_server_used_memory{cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (cluster) (irate (endpoint_read_requests{cluster=\"$cluster\"}[1m]))) + (sum by (cluster) (irate(endpoint_write_requests{cluster=\"$cluster\"}[1m]))) + (sum by(cluster) (irate (endpoint_other_requests{cluster=\"$cluster\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$db",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "repeat": "db",
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(cluster, db)(redis_server_used_memory{cluster=\"$cluster\", db=\"$db\"}) / sum by(cluster, db)(redis_server_maxmemory{cluster=\"$cluster\", db=\"$db\"})"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (cluster, db)(irate(endpoint_read_requests_latency_histogram_sum{cluster=\"$cluster\", db=\"$db\"}[1m]))  + sum by(cluster, db) (irate(endpoint_write_requests_latency_histogram_sum{cluster=\"$cluster\", db=\"$db\"}[1m]) ) + sum by (cluster, db) (irate(endpoint_other_requests_latency_histogram_sum{cluster=\"$cluster\", db=\"$db\"}[1m]))) / ((sum by (cluster, db) (irate(endpoint_read_requests{cluster=\"$cluster\", db=\"$db\"}[1m]))) + (sum by(cluster, db)(irate(endpoint_write_requests{cluster=\"$cluster\", db=\"$db\"}[1m]))) + (sum by(cluster, db)(irate(endpoint_other_requests{cluster=\"$cluster\", db=\"$db\"}[1m])))) / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Operations",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(cluster, db)(irate(endpoint_read_requests{cluster=\"$cluster\", db=\"$db\"}[1m]) + irate(endpoint_write_requests{cluster=\"$cluster\", db=\"$db\"}[1m]) + irate(endpoint_other_requests{cluster=\"$cluster\", db=\"$db\"}[1m]))"
    }
   ]
  },
  {
   "title": "Expiration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(cluster) (irate(redis_server_expired_keys{role=\"master\", cluster=\"$cluster\"}[1m]))"
    }
   ]
  },
  {
   "title": "Key Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(sum by(cluster, db)(redis_server_db_keys{role=\"master\", cluster=\"$cluster\", db=\"$db\"}))"
    }
   ]
  },
  {
   "title": "Connection Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(sum by(cluster, db)(endpoint_client_connections{cluster=\"$cluster\", db=\"$db\"} - endpoint_client_disconnections{cluster=\"$cluster\", db=\"$db\"}))"
    }
   ]
  }
 ]
}
{
 "title": "Database Status Dashboard",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(redis_server_up,cluster)"
    }
   },
   {
    "name": "db",
    "label": "db",
    "query": {
     "query": "label_values(endpoint_client_connections{cluster=\"$cluster\"},db)"
    }
   },
   {
    "name": "aggregation",
    "label": "aggregation interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(sum(irate(endpoint_read_requests_latency_histogram_sum{db=\"$db\"}[1m]))/sum(irate(endpoint_read_requests{db=\"$db\"}[1m])))/1000000",
     "legendFormat": "Read"
    },
    {
     "expr": "(sum(irate(endpoint_write_requests_latency_histogram_sum{db=\"$db\"}[1m]))/sum(irate(endpoint_write_requests{db=\"$db\"}[1m])))/1000000",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (db,cluster) (redis_server_used_memory{db=\"$db\", cluster=\"$cluster\"}) / sum by (db,cluster) (redis_server_maxmemory{db=\"$db\", cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Operations",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (db, cluster) (irate(endpoint_read_requests{db=\"$db\", cluster=\"$cluster\"}[1m]) + irate(endpoint_write_requests{db=\"$db\", cluster=\"$cluster\"}[1m]) + irate(endpoint_other_requests{db=\"$db\", cluster=\"$cluster\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Operations",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sum by (db, cluster) (irate(endpoint_read_requests{db=\"$db\", cluster=\"$cluster\"}[1m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum by (db, cluster) (irate(endpoint_write_requests{db=\"$db\", cluster=\"$cluster\"}[1m]))",
     "legendFormat": "write"
    },
    {
     "expr": "sum by(db, cluster) (irate(endpoint_other_requests{db=\"$db\", cluster=\"$cluster\"}[1m]))",
     "legendFormat": "other"
    }
   ]
  },
  {
   "title": "Key Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(sum by (db, cluster) (redis_server_db_keys{role=\"master\", db=\"$db\", cluster=\"$cluster\"}))"
    }
   ]
  },
  {
   "title": "Expired Keys",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (db, cluster) (irate(redis_server_expired_keys{role=\"master\", cluster=\"$cluster\", db=\"$db\"}[1m]))",
     "legendFormat": "Expired Keys"
    }
   ]
  },
  {
   "title": "Connection Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(sum by (db, cluster) (endpoint_client_connections{cluster=\"$cluster\", db=\"$db\"} - endpoint_client_disconnections{cluster=\"$cluster\", db=\"$db\"}))"
    }
   ]
  },
  {
   "title": "Total Misses",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (db, cluster) (irate(redis_server_keyspace_read_misses{role=\"master\", cluster=\"$cluster\", db=\"$db\"}[1m]))) + (sum by (db, cluster) (irate(redis_server_keyspace_write_misses{role=\"master\", cluster=\"$cluster\", db=\"$db\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System CPU",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(db, cluster) (irate(namedprocess_namegroup_thread_cpu_seconds_total{mode=\"system\", threadname=~\"redis-server.*\", cluster=\"$cluster\", db=\"$db\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "User CPU",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(db, cluster) (irate(namedprocess_namegroup_thread_cpu_seconds_total{mode=\"user\", threadname=~\"redis-server.*\", db=\"$db\", cluster=\"$cluster\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}
{
 "title": "Node Dashboard",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(node_metrics_up,cluster)"
    }
   },
   {
    "name": "node",
    "query": {
     "query": "label_values(node_metrics_up{cluster=\"$cluster\"}, node)"
    }
   },
   {
    "name": "version",
    "query": {
     "query": "label_values(node_config{cluster=\"$cluster\",node=\"$node\"}, cnm_version)"
    }
   },
   {
    "name": "aggregation",
    "label": "interval aggregation",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Node $node : Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Database Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(redis_server_used_memory{cluster=\"$cluster\", node=\"$node\"}) by (bdb))"
    }
   ]
  },
  {
   "title": "Master Shard Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(redis_server_used_memory{cluster=\"$cluster\", node=\"$node\", role=\"master\"})"
    }
   ]
  },
  {
   "title": "Replica Shard Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(redis_server_used_memory{cluster=\"$cluster\", node=\"$node\", role=\"slave\"})"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(avg by(node) (irate(node_cpu_seconds_total{mode=\"system\", cluster=\"$cluster\", node=\"$node\"}[1m]))) + (avg by(node) (irate(node_cpu_seconds_total{mode=\"user\", cluster=\"$cluster\", node=\"$node\"}[1m])))"
    }
   ]
  },
  {
   "title": "Free Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_available_memory_bytes{cluster=\"$cluster\",node=\"$node\"}"
    }
   ]
  },
  {
   "title": "Version",
   "type": "text",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "options": {
    "content": "<br>\n<center>\n  <b style=\"font-size: 20pt\">$version<b>\n</center>\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Node $node : CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage on Node",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percentunit", "label": "percents" }
   ],
   "targets": [
    {
     "expr": "(avg by(node) (irate(node_cpu_seconds_total{mode=\"system\", cluster=\"$cluster\", node=\"$node\"}[1m]))) + (avg by(node) (irate(node_cpu_seconds_total{mode=\"user\", cluster=\"$cluster\", node=\"$node\"}[1m])))",
     "legendFormat": "user+system"
    },
    {
     "expr": "1- (avg by(node)(irate(node_cpu_seconds_total{mode=\"idle\",cluster=\"$cluster\", node=\"$node\"}[1m]))) - (avg by(node)(irate(node_cpu_seconds_total{mode=\"system\",cluster=\"$cluster\", node=\"$node\"}[1m]))) - (avg by(node)(irate(node_cpu_seconds_total{mode=\"user\",cluster=\"$cluster\", node=\"$node\"}[1m]))) unless (avg by(node)(irate(node_cpu_seconds_total{mode=\"nice\",cluster=\"$cluster\", node=\"$node\"}[1m])))",
     "legendFormat": "other"
    },
    {
     "expr": "avg by(node)(irate(dmcproxy_process_cpu_user_seconds_total{cluster=\"$cluster\", node=\"$node\"}[1m]))",
     "legendFormat": "dmcproxy (100% = 1 core)"
    },
    {
     "expr": "avg by(node)(irate(node_cpu_seconds_total{mode=~\"system|user\", cluster=\"$cluster\", node=\"$node\"}[1m]))",
     "legendFormat": "shards (100% = 1 core)"
    }
   ]
  },
  {
   "title": "Node Traffic",
   "type": "timeseries",
   "description": "display the egress and ingress traffic on the node's NIC",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "Bps", "label": "Egress bytes/sec " }
   ],
   "targets": [
    {
     "expr": "sum by(node)(irate(node_network_receive_bytes_total{cluster=\"$cluster\", node=\"$node\"}[1m]))",
     "legendFormat": "Ingress for node {{node}}"
    },
    {
     "expr": "sum by(node)(irate(node_network_transmit_bytes_total{cluster=\"$cluster\", node=\"$node\"}[1m]))",
     "legendFormat": "egress for node {{node}}"
    }
   ]
  },
  {
   "title": "Fragmentation",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(redis_server_allocator_active{node=\"$node\",cluster=\"$cluster\"} / redis_server_allocator_allocated{node=\"$node\",cluster=\"$cluster\"}) - 1",
     "legendFormat": "active / allocated (defraggable)"
    },
    {
     "expr": "avg(redis_server_allocator_resident{node=\"$node\",cluster=\"$cluster\"} / redis_server_allocator_active{node=\"$node\",cluster=\"$cluster\"}) - 1",
     "legendFormat": "resident / active (purgable)"
    },
    {
     "expr": "sum(redis_server_allocator_active{node=\"$node\",cluster=\"$cluster\"} - redis_server_allocator_allocated{node=\"$node\",cluster=\"$cluster\"})",
     "legendFormat": "active - allocated (defraggable)"
    },
    {
     "expr": "sum(redis_server_allocator_resident{node=\"$node\",cluster=\"$cluster\"} - redis_server_allocator_active{node=\"$node\",cluster=\"$cluster\"})",
     "legendFormat": "resident - active (purgable)"
    },
    {
     "expr": "avg(redis_server_active_defrag_running{node=\"$node\",cluster=\"$cluster\"})/100",
     "legendFormat": "active defrag running"
    },
    {
     "expr": "sum(namedprocess_namegroup_memory_bytes{memtype=\"resident\", node=\"$node\",cluster=\"$cluster\"}) - sum(redis_server_allocator_resident{node=\"$node\",cluster=\"$cluster\"})",
     "legendFormat": "process rss - allocator rss"
    },
    {
     "expr": "sum(namedprocess_namegroup_memory_bytes{memtype=\"resident\", node=\"$node\",cluster=\"$cluster\"}) / sum(redis_server_allocator_resident{node=\"$node\",cluster=\"$cluster\"})",
     "legendFormat": "process rss / allocator rss"
    }
   ]
  },
  {
   "title": "Top 10 Shards by Used Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "topk(10, redis_server_used_memory{cluster=\"$cluster\", node=\"$node\"})",
     "legendFormat": "redis:{{redis}}, bdb:{{bdb}},  role:{{role}}"
    },
    {
     "expr": "dmcproxy_process_resident_memory_bytes{cluster=\"$cluster\", node=\"$node\"}",
     "legendFormat": "dmcproxy"
    }
   ]
  }
 ]
}
{
 "title": "Shard Dashboard",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(redis_server_up,cluster)"
    }
   },
   {
    "name": "newStatus",
    "query": {
     "query": "label_values(redis_server_connected_clients{db=\"$db\", cluster=\"$cluster\"}, status)"
    }
   },
   {
    "name": "db",
    "label": "database",
    "query": {
     "query": "label_values(endpoint_client_connections{cluster=\"$cluster\"},db)"
    }
   },
   {
    "name": "shard",
    "label": "shard",
    "query": {
     "query": "label_values(redis_server_up{cluster=\"$cluster\", db=\"$db\"}, redis)"
    }
   },
   {
    "name": "aggregation",
    "label": "aggregation interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "$db : shard $shard : Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "text",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": {
    "content": "<br>\n<center>\n<b style=\"font-size: 20pt\">$newStatus<b>\n</center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(sum by(db)(irate(namedprocess_namegroup_cpu_seconds_total{mode=~\"system|user\", cluster=\"$cluster\",db=\"$db\", redis=\"$shard\"}[1m])))"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(redis_server_used_memory{db=\"$db\", cluster=\"$cluster\", redis=\"$shard\"})"
    }
   ]
  },
  {
   "title": "Key Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_server_db_keys{db=\"$db\", cluster=\"$cluster\", redis=\"$shard\"}"
    }
   ]
  },
  {
   "title": "Connection Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(redis_server_connected_clients{db=\"$db\", cluster=\"$cluster\", redis=\"$shard\"})"
    }
   ]
  },
  {
   "title": "Forwarding",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(redis_server_forwarding_state{cluster=\"$cluster\", db=\"$db\", redis=\"$shard\"})"
    }
   ]
  },
  {
   "title": "$db : shard $shard : Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Max Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "redis_server_maxmemory{cluster=\"$cluster\", db=\"$db\", redis=\"$shard\"}",
     "legendFormat": "shard {{redis}}"
    }
   ]
  },
  {
   "title": "Allocated Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "redis_server_allocator_allocated{cluster=\"$cluster\", db=\"$db\", redis=\"$shard\"}",
     "legendFormat": "shard {{redis}}"
    }
   ]
  },
  {
   "title": "Resident Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "redis_server_allocator_resident{cluster=\"$cluster\", db=\"$db\", redis=\"$shard\"}",
     "legendFormat": "shard {{redis}}"
    }
   ]
  },
  {
   "title": "Process Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "redis_server_allocator_allocated{cluster=\"$cluster\", db=\"$db\", redis=\"$shard\"}",
     "legendFormat": "shard {{redis}}"
    }
   ]
  },
  {
   "title": "Fragmentation Ratio",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "redis_server_mem_fragmentation_ratio{db=\"$db\", cluster=\"$cluster\", redis=\"$shard\"}",
     "legendFormat": "shard {{redis}}"
    }
   ]
  },
  {
   "title": "AOF Buffer",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "redis_server_mem_aof_buffer{db=\"$db\", cluster=\"$cluster\", redis=\"$shard\"}",
     "legendFormat": "shard {{redis}}"
    }
   ]
  },
  {
   "title": "Memory less Eviction",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "redis_server_mem_not_counted_for_evict{cluster=\"$cluster\", db=\"$db\", redis=\"$shard\"}",
     "legendFormat": "shard {{redis}}"
    }
   ]
  },
  {
   "title": "Replication Backlog",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "redis_server_mem_replication_backlog{db=\"$db\", cluster=\"$cluster\", redis=\"$shard\"}",
     "legendFormat": "shard {{redis}}"
    }
   ]
  },
  {
   "title": "$db : shard $shard : CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Process CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(namedprocess_namegroup_cpu_seconds_total{db=\"$db\", cluster=\"$cluster\", redis=\"$shard\", mode=\"system\"}[1m])",
     "legendFormat": "System CPU"
    },
    {
     "expr": "rate(namedprocess_namegroup_cpu_seconds_total{db=\"$db\", cluster=\"$cluster\", redis=\"$shard\", mode=\"user\"}[1m])",
     "legendFormat": "User CPU"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (redis)(rate(namedprocess_namegroup_cpu_seconds_total{mode=~\"system|user\", redis=\"$shard\", cluster=\"$cluster\", db=\"$db\"}[1m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Main Thread",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(namedprocess_namegroup_cpu_seconds_total{redis=\"$shard\", mode=\"system\", cluster=\"$cluster\", db=\"$db\"}[1m])",
     "legendFormat": "Main Thread - System"
    },
    {
     "expr": "rate(namedprocess_namegroup_cpu_seconds_total{redis=\"$shard\", mode=\"user\", cluster=\"$cluster\", db=\"$db\"}[1m])",
     "legendFormat": "Main Thread - User"
    }
   ]
  },
  {
   "title": "$db : shard $shard : Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "redis_server_connected_clients{db=\"$db\", cluster=\"$cluster\", redis=\"$shard\"} ",
     "legendFormat": "Total"
    },
    {}
   ]
  },
  {
   "title": "Commands Processed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(redis_server_total_commands_processed{db=\"$db\", cluster=\"$cluster\", redis=\"$shard\"}[1m])",
     "legendFormat": "Connected Clients"
    }
   ]
  },
  {
   "title": "Ingress/Egress",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(redis_server_total_net_output_bytes{db=\"$db\", cluster=\"$cluster\", redis=\"$shard\"}[1m])",
     "legendFormat": "Egress"
    },
    {
     "expr": "rate(redis_server_total_net_input_bytes{db=\"$db\", cluster=\"$cluster\", redis=\"$shard\"}[1m])",
     "legendFormat": "Ingress"
    }
   ]
  },
  {
   "title": "$db : shard $shard : Keys",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Keys per Shard",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(sum by (db) (redis_server_db_keys{role=\"master\", cluster=\"$cluster\", db=\"$db\"})) / (count by(db) (redis_server_db_keys{role=\"maste\", cluster=\"$cluster\", db=\"$db\"}))",
     "legendFormat": "shard:{{redis}}, role: {{role}}, node:{{node}}, slots:{{slots}}"
    }
   ]
  },
  {
   "title": "Total Keys",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "redis_server_db_keys{cluster=\"$cluster\", db=\"$db\", redis=\"$shard\"}",
     "legendFormat": "shard: {{redis}}"
    }
   ]
  },
  {
   "title": "Evicted Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "redis_server_evicted_keys{db=\"$db\", cluster=\"$cluster\", redis=\"$shard\"}",
     "legendFormat": "shard: {{redis}}"
    }
   ]
  },
  {
   "title": "Expired Keys",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "redis_server_expired_keys{db=\"$db\", cluster=\"$cluster\", redis=\"$shard\"}",
     "legendFormat": "shard: {{redis}}"
    }
   ]
  },
  {
   "title": "$db : shard $shard : Cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Fragmentation",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(redis_server_mem_fragmentation_ratio{db=\"$db\",cluster=\"$cluster\", redis=\"$shard\"}) / count(redis_server_mem_fragmentation_ratio{db=\"$db\",cluster=\"$cluster\", redis=\"$shard\"})",
     "legendFormat": "redis_mem_fragmentation_ratio"
    },
    {
     "expr": "sum(redis_server_allocator_active{db=\"$db\",cluster=\"$cluster\", redis=\"$shard\"}) / sum(redis_server_allocator_allocated{db=\"$db\",cluster=\"$cluster\", redis=\"$shard\"})",
     "legendFormat": "Shard allocator fragmentation"
    },
    {
     "expr": "sum(redis_server_allocator_resident{db=\"$db\",cluster=\"$cluster\", redis=\"$shard\"}) / sum(redis_server_allocator_active{db=\"$db\",cluster=\"$cluster\", redis=\"$shard\"})",
     "legendFormat": "shard allocator rss"
    }
   ]
  },
  {
   "title": "Shard RSS Fragmentation",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "redis_server_mem_fragmentation_ratio{cluster=\"$cluster\", db=\"$db\", redis=\"$shard\"} ",
     "legendFormat": "shard:{{redis}} role:{{role}}"
    }
   ]
  },
  {
   "title": "Shard Allocation Fragmentation (#)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "redis_server_allocator_active{db=\"$db\",cluster=\"$cluster\", redis=\"$shard\"} - redis_server_allocator_allocated{db=\"$db\",cluster=\"$cluster\", redis=\"$shard\"}",
     "legendFormat": "shard:{{redis}} role:{{role}}"
    }
   ]
  },
  {
   "title": "Shard Allocation Fragmentation (%)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "redis_server_allocator_active{db=\"$db\",cluster=\"$cluster\", redis=\"$shard\"} / redis_server_allocator_allocated{db=\"$db\",cluster=\"$cluster\", redis=\"$shard\"}",
     "legendFormat": "shard:{{redis}} role:{{role}}"
    }
   ]
  },
  {
   "title": "$db : shard $shard : ROF Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Used Memory(ROF) for db",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "redis_server_used_ram{db=\"$db\", cluster=\"$cluster\", role=\"master\"}",
       "legendFormat": "Used RAM"
      },
      {
       "expr": "redis_server_max_ram{db=\"$db\", cluster=\"$cluster\", role=\"master\"}",
       "legendFormat": "limit (when low, near used)"
      }
     ]
    },
    {
     "title": "DB ram hit ratio",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg by(db)((redis_server_ram_fetch_hit_ratio_ram{db=\"$db\", cluster=\"$cluster\"} + redis_server_ram_write_hit_ratio_ram{db=\"$db\", cluster=\"$cluster\"} + redis_server_ram_del_hit_ratio_ram{db=\"$db\", cluster=\"$cluster\"}) / (redis_server_ram_fetch_hit_ratio_flash{db=\"$db\", cluster=\"$cluster\"} + redis_server_ram_write_hit_ratio_flash{db=\"$db\", cluster=\"$cluster\"} + redis_server_ram_del_hit_ratio_flash{db=\"$db\", cluster=\"$cluster\"} + redis_server_ram_fetch_hit_ratio_ram{db=\"$db\", cluster=\"$cluster\"} + redis_server_ram_write_hit_ratio_ram{db=\"$db\", cluster=\"$cluster\"} + redis_server_ram_del_hit_ratio_ram{db=\"$db\", cluster=\"$cluster\"})) > 0",
       "legendFormat": "DB ram hit ratio"
      },
      {
       "expr": "(avg by (db)(redis_server_ram_fetch_hit_ratio_ram{cluster=\"$cluster\", db=\"$db\"} / (redis_server_ram_fetch_hit_ratio_flash{cluster=\"$cluster\", db=\"$db\"} + redis_server_ram_fetch_hit_ratio_ram{cluster=\"$cluster\", db=\"$db\"}))) > 0",
       "legendFormat": "read hit ratio"
      },
      {
       "expr": "avg by(db) (redis_server_ram_write_hit_ratio_ram{cluster=\"$cluster\", db=\"$db\"}/(redis_server_ram_write_hit_ratio_flash{cluster=\"$cluster\", db=\"$db\"}+redis_server_ram_write_hit_ratio_ram{cluster=\"$cluster\", db=\"$db\"})) > 0",
       "legendFormat": "write hit ratio"
      },
      {
       "expr": "avg by(db) (redis_server_ram_del_hit_ratio_ram{cluster=\"$cluster\", db=\"$db\"}/(redis_server_ram_del_hit_ratio_flash{cluster=\"$cluster\", db=\"$db\"}+redis_server_ram_del_hit_ratio_ram{cluster=\"$cluster\", db=\"$db\"})) > 0",
       "legendFormat": "del hit ratio"
      }
     ]
    },
    {
     "title": "RAM:Flash access ratio",
     "type": "timeseries",
     "description": "Positive is RAM, Negative is Flash",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "avg(delta(redis_server_big_io_ratio_redis{cluster=\"$cluster\",db=\"$db\",role=\"master\"}[1m]))/60",
       "legendFormat": "RAM Ops for Redis"
      },
      {
       "expr": "avg(delta(redis_server_big_io_ratio_flash{cluster=\"$cluster\",db=\"$db\",role=\"master\"}[1m]) * -1)/60",
       "legendFormat": "Flash Ops for Redis"
      },
      {
       "expr": "avg(delta(redis_server_big_user_io_ratio_redis{cluster=\"$cluster\",db=\"$db\",role=\"master\"}[1m]))/60",
       "legendFormat": "User RAM Ops for Redis"
      },
      {
       "expr": "avg(delta(redis_server_big_user_io_ratio_flash{cluster=\"$cluster\",db=\"$db\",role=\"master\"}[1m]) * -1)/60",
       "legendFormat": "User Flash Ops for Redis"
      }
     ]
    },
    {
     "title": "RAM:Flash access ratio",
     "type": "timeseries",
     "description": "Positive is RAM, Negative is Flash",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "delta(redis_server_big_io_ratio_redis{cluster=\"$cluster\",db=\"$db\"}[1m])/60",
       "legendFormat": "RAM Ops for Redis {{redis}}"
      },
      {
       "expr": "delta(redis_server_big_io_ratio_flash{cluster=\"$cluster\",db=\"$db\"}[1m]) / -60",
       "legendFormat": "Flash Ops for Redis {{redis}}"
      }
     ]
    },
    {
     "title": "Flash IO Banwidth",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg by(db)(redis_server_big_io_reads{db=\"$db\", cluster=\"$cluster\"})",
       "legendFormat": "Reads"
      },
      {
       "expr": "avg by(db)(redis_server_big_io_writes{db=\"$db\", cluster=\"$cluster\"})",
       "legendFormat": "Writes"
      }
     ]
    },
    {
     "title": "Flash IOPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (db)(redis_server_big_io_reads{db=\"$db\", cluster=\"$cluster\"})",
       "legendFormat": "Reads"
      },
      {
       "expr": "sum by (db)(redis_server_big_io_writes{db=\"$db\", cluster=\"$cluster\"})",
       "legendFormat": "Writes"
      },
      {
       "expr": "sum by (db)(redis_server_big_io_dels{db=\"$db\", cluster=\"$cluster\"})",
       "legendFormat": "Deletes"
      }
     ]
    },
    {
     "title": "DB sum redis wait busy key / $aggregation",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(delta(redis_server_wait_busy_key{db=\"$db\",cluster=\"$cluster\"}[$aggregation]))",
       "legendFormat": "db:{{$db}}"
      }
     ]
    },
    {
     "title": "DB sum redis blocking reads / $aggregation",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(delta(redis_server_blocking_reads{db=\"$db\",cluster=\"$cluster\"}[$aggregation]))",
       "legendFormat": "db:{{$db}}"
      }
     ]
    },
    {
     "title": "DB used flash",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (db)(redis_server_used_disk{db=\"$db\",cluster=\"$cluster\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum by(db)(redis_server_used_disk{db=\"$db\",cluster=\"$cluster\"}) * avg by(db) (redis_server_disk_fragmentation_ratio{db=\"$db\",cluster=\"$cluster\"})",
       "legendFormat": "actual"
      },
      {
       "expr": "avg by (db)(redis_server_disk_fragmentation_ratio{db=\"$db\",cluster=\"$cluster\"})",
       "legendFormat": "frag ratio"
      }
     ]
    },
    {
     "title": "DB postponed clients",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (db)(redis_server_big_inst_avg_io_postponed_clients{cluster=\"$cluster\",db=\"$db\"})",
       "legendFormat": "db:{{$db}}"
      }
     ]
    },
    {
     "title": "DB blocked clients",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (db)(redis_server_big_inst_avg_io_blocked_clients{db=\"$db\",cluster=\"$cluster\"})",
       "legendFormat": "Number of blocked clients"
      }
     ]
    },
    {
     "title": "DB ram overhead",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by (db)(redis_server_ram_overhead{cluster=\"$cluster\",db=\"$db\", role=\"master\"})  / sum by(db) (redis_server_used_ram{cluster=\"$cluster\",db=\"$db\",role=\"master\"})",
       "legendFormat": "Total Ratio"
      },
      {
       "expr": "sum by (db, role)(redis_server_ram_overhead{cluster=\"$cluster\",db=\"$db\"})  / sum by(db,role) (redis_server_max_ram{cluster=\"$cluster\",db=\"$db\"})",
       "legendFormat": "db: {{db}} role:{{role}}"
      }
     ]
    },
    {
     "title": "DB sum redis blocking writes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(db)(rate(redis_server_blocking_writes{db=\"$db\",cluster=\"$cluster\"}[1m]))",
       "legendFormat": "db:{{db}}"
      }
     ]
    },
    {
     "title": "DB sum redis big inst avg read io queue",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (db)(redis_server_big_inst_avg_read_io_queue{db=\"$db\",cluster=\"$cluster\"})",
       "legendFormat": "db:{{db}}"
      }
     ]
    },
    {
     "title": "DB sum redis big inst avg write io queue",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (db)(redis_server_big_inst_avg_write_io_queue{db=\"$db\",cluster=\"$cluster\"})",
       "legendFormat": "db:{{db}}"
      }
     ]
    },
    {
     "title": "DB objects(values) in FLASH",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 95 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(db)(redis_server_bigdb_disk{db=\"$db\",cluster=\"$cluster\", role=\"master\"})",
       "legendFormat": "objects in flash (sum of all master shards)"
      },
      {
       "expr": "sum by (db)(redis_server_bigdb_ram{db=\"$db\",cluster=\"$cluster\", role=\"master\"})",
       "legendFormat": "objects in ram (sum of all master shards)"
      }
     ]
    },
    {
     "title": "DB % values in RAM",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 95 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by(db,cluster)(redis_server_bigdb_ram{db=\"$db\",cluster=\"$cluster\", role=\"master\"}) / sum by (db,cluster)(redis_server_db_keys{db=\"$db\",cluster=\"$cluster\",role=\"master\"})",
       "legendFormat": "DB % values in RAM (masters)"
      },
      {
       "expr": "avg((max(redis_server_bigdb_ram{db=\"$db\",cluster=\"$cluster\",role=\"master\"}) by (redis,db,cluster)) / on (redis,db,cluster) redis_server_db_keys{db=\"$db\",cluster=\"$cluster\",role=\"master\"})",
       "legendFormat": "average master shard % values in RAM"
      },
      {
       "expr": "avg((max(redis_server_bigdb_ram{db=\"$db\",cluster=\"$cluster\",role=\"slave\"}) by (redis,db,cluster)) / on (redis,db,cluster) redis_server_db_keys{db=\"$db\",cluster=\"$cluster\",role=\"slave\"})",
       "legendFormat": "average slave shard % values in RAM"
      },
      {
       "expr": "topk(1, min((max(redis_server_bigdb_ram{db=\"$db\",cluster=\"$cluster\",role=\"master\"}) by (redis,db,cluster)) / on (redis,db,cluster) redis_server_db_keys{db=\"$db\",cluster=\"$cluster\",role=\"master\"}) by (redis) * -1) *-1",
       "legendFormat": "lowest master shard % values in RAM - redis:{{redis}}"
      },
      {
       "expr": "topk(1, min((max(redis_server_bigdb_ram{db=\"$db\",cluster=\"$cluster\",role=\"slave\"}) by (redis,db,cluster)) / on (redis,db,cluster) redis_server_db_keys{db=\"$db\",cluster=\"$cluster\",role=\"slave\"}) by (redis) * -1) *-1",
       "legendFormat": "lowest slave shard % values in RAM - redis:{{redis}}"
      }
     ]
    },
    {
     "title": "Shard objects(values) in RAM",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 95 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg(max(redis_server_bigdb_ram{db=\"$db\",cluster=\"$cluster\",role=\"slave\"}))",
       "legendFormat": "average number of values in ram per slave shard"
      },
      {
       "expr": "avg(max(redis_server_bigdb_ram{db=\"$db\",cluster=\"$cluster\",role=\"master\"}))",
       "legendFormat": "average number of values in ram per master shard"
      },
      {
       "expr": "min by(redis)(redis_server_bigdb_ram{role=\"slave\", cluster=\"$cluster\", db=\"$db\"})",
       "legendFormat": "lowest number of values in ram per slave shard - redis:{{redis}}"
      },
      {
       "expr": "min by(redis)(redis_server_bigdb_ram{role=\"master\", cluster=\"$cluster\", db=\"$db\"})",
       "legendFormat": "lowest number of values in ram per master shard  - redis:{{redis}}"
      }
     ]
    },
    {
     "title": "DB dirty RAM evictions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 103 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "redis_server_ram_dirty_evictions{db=\"$db\",cluster=\"$cluster\", role=\"master\"}",
       "legendFormat": "db:{{db}}"
      }
     ]
    },
    {
     "title": "DB clean RAM evictions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 103 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "redis_server_ram_clean_evictions{db=\"$db\",cluster=\"$cluster\", role=\"master\"}",
       "legendFormat": "db:{{db}}"
      }
     ]
    },
    {
     "title": "RocksDB",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 103 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(delta(redis_server_rocks_comp_started{db=\"$db\", cluster=\"$cluster\", role=\"master\"}[1m]))",
       "legendFormat": "compactions"
      },
      {
       "expr": "sum(delta(redis_server_rocks_flush_started{db=\"$db\", cluster=\"$cluster\"}[1m]))",
       "legendFormat": "flushes"
      },
      {
       "expr": "sum(delta(redis_server_rocks_flush_writes_slowdown{db=\"$db\", cluster=\"$cluster\"}[$aggregation]))",
       "legendFormat": "slowdowns / $aggregation"
      },
      {
       "expr": "sum(delta(redis_server_rocks_flush_writes_stop{db=\"$db\", cluster=\"$cluster\"}[$aggregation]))",
       "legendFormat": "stalls / $aggregation"
      }
     ]
    }
   ]
  }
 ]
}