---
# Grafana Instance
# Purpose: Deploy Grafana instance for Redis Enterprise monitoring
# Managed by: Platform Team

apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana-redis-monitoring
  namespace: openshift-monitoring
  labels:
    dashboards: "grafana"
    app: grafana
spec:
  config:
    log:
      mode: "console"
    auth:
      disable_login_form: "false"
    security:
      admin_user: "admin"
      admin_password: "admin"

