---
# Namespace for Redis Databases - Development
# Team: Team 2
# Purpose: Development Redis databases (session)

apiVersion: v1
kind: Namespace
metadata:
  name: redis-team2-dev
  labels:
    # Team ownership
    team: team2

    # Environment
    environment: dev

    # Cost allocation
    cost-center: CC-TEAM2

    # Application
    app: redis-enterprise

    # Redis Enterprise multi-namespace support
    redis-db-namespace: enabled

    # Governance
    managed-by: platform-team
    gitops: argocd

    # OpenShift features
    openshift.io/cluster-monitoring: "true"
  
  annotations:
    description: "Development Redis databases for Team 2 (session)"
    owner: "team2@company.com"
    created-by: "platform-team"
    quota-profile: "dev"

