[req]
default_bits       = 2048
prompt             = no
default_md         = sha256
distinguished_name = dn
req_extensions     = v3_req

[dn]
C  = BR
ST = SP
L  = Sao Paulo
O  = DemoRedis
CN = redis-demo.example.com

[v3_req]
keyUsage         = keyEncipherment, dataEncipherment
extendedKeyUsage = serverAuth
subjectAltName   = @alt_names

[alt_names]
DNS.1 = redis-demo.example.com
DNS.2 = *.redis-demo.example.com
DNS.3 = *.redis-enterprise.svc.cluster.local
DNS.4 = *.redis-team1-dev.svc.cluster.local
DNS.5 = *.redis-team1-prod.svc.cluster.local
DNS.6 = *.redis-team2-dev.svc.cluster.local
DNS.7 = *.redis-team2-prod.svc.cluster.local
DNS.8 = *.redis-enterprise.svc
DNS.9 = *.redis-team1-dev.svc
DNS.10 = *.redis-team1-prod.svc
DNS.11 = *.redis-team2-dev.svc
DNS.12 = *.redis-team2-prod.svc
IP.1  = 127.0.0.1
