---
# RBAC for Argo CD to manage ServiceMonitors
# Purpose: Allow Argo CD to create/manage ServiceMonitor resources for Redis monitoring
# Managed by: Platform Team

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-servicemonitor-manager
  labels:
    app.kubernetes.io/part-of: argocd
    managed-by: platform-team
rules:
  # ServiceMonitor permissions
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - servicemonitors
    verbs:
      - create
      - get
      - list
      - watch
      - update
      - patch
      - delete
  
  # PrometheusRule permissions (for alerts)
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - prometheusrules
    verbs:
      - create
      - get
      - list
      - watch
      - update
      - patch
      - delete

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-servicemonitor-manager
  labels:
    app.kubernetes.io/part-of: argocd
    managed-by: platform-team
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argocd-servicemonitor-manager
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    namespace: openshift-gitops

