---
# ClusterRole to allow ArgoCD to manage platform resources
# Includes: Gatekeeper, ResourceQuotas, LimitRanges
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-platform-manager
  labels:
    app: argocd
    managed-by: platform-team
rules:
  # Gatekeeper Operator resources
  - apiGroups:
      - operator.gatekeeper.sh
    resources:
      - gatekeepers
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - operator.gatekeeper.sh
    resources:
      - gatekeepers/status
    verbs:
      - get
      - list
      - watch

  # Gatekeeper ConstraintTemplates (creates policy CRDs)
  - apiGroups:
      - templates.gatekeeper.sh
    resources:
      - constrainttemplates
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

  # Gatekeeper Constraints (all constraint types)
  - apiGroups:
      - constraints.gatekeeper.sh
    resources:
      - '*'
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

  # ResourceQuotas (core API group)
  - apiGroups:
      - ""
    resources:
      - resourcequotas
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

  # LimitRanges (core API group)
  - apiGroups:
      - ""
    resources:
      - limitranges
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

  # Services (core API group)
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

  # ServiceAccounts (core API group)
  - apiGroups:
      - ""
    resources:
      - serviceaccounts
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

  # Jobs (batch API group)
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

  # Redis Enterprise Clusters (app.redislabs.com)
  - apiGroups:
      - app.redislabs.com
    resources:
      - redisenterpriseclusters
      - redisenterprisedatabases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

  # ServiceMonitors and PrometheusRules (monitoring.coreos.com)
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - servicemonitors
      - prometheusrules
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

  # Grafana resources (grafana.integreatly.org)
  - apiGroups:
      - grafana.integreatly.org
    resources:
      - grafanas
      - grafanadatasources
      - grafanadashboards
      - grafanafolders
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

  # Routes (route.openshift.io)
  - apiGroups:
      - route.openshift.io
    resources:
      - routes
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
---
# ClusterRoleBinding to grant ArgoCD application controller the permissions
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-platform-manager
  labels:
    app: argocd
    managed-by: platform-team
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argocd-platform-manager
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    namespace: openshift-gitops

