---
# Redis Enterprise Cluster
apiVersion: app.redislabs.com/v1
kind: RedisEnterpriseCluster
metadata:
  name: demo-cluster
  namespace: redis-demo
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  # Small cluster for demo - 3 nodes
  nodes: 3

  # Persistent storage
  persistentSpec:
    enabled: true
    storageClassName: "ocs-external-storagecluster-ceph-rbd"
    volumeSize: 10Gi

  # Redis Enterprise version
  redisEnterpriseNodeResources:
    limits:
      cpu: '2'
      memory: 4Gi
    requests:
      cpu: '1'
      memory: 2Gi

  # UI Service
  uiServiceType: ClusterIP

  # License (uses default trial license)
  # For production, add your license key here

  # TLS Certificate Configuration
  # Uncomment the lines below after creating the certificate:
  # certificates:
  #   apiCertificateSecretName: redis-cluster-tls

