---
# Redis Database for Order Data
apiVersion: app.redislabs.com/v1alpha1
kind: RedisEnterpriseDatabase
metadata:
  name: orders
  namespace: redis-demo
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  # Database name
  name: orders-db
  
  # Memory size
  memorySize: 100MB
  
  # Replication for high availability
  replication: true
  
  # Persistence
  persistence: aofEverySecond
  
  # TLS (disabled for demo simplicity)
  tlsMode: disabled
  
  # Redis Enterprise Cluster reference
  redisEnterpriseCluster:
    name: demo-cluster
  
  # Database type
  type: redis
  
  # Eviction policy
  evictionPolicy: allkeys-lru

