---
# LimitRange for Development Namespaces
# Purpose: Set default and maximum resource limits for containers
# Managed by: Platform Team
# Applied to: redis-*-dev namespaces

apiVersion: v1
kind: LimitRange
metadata:
  name: redis-dev-limits
  labels:
    environment: dev
    managed-by: platform-team
    resource-type: limitrange
spec:
  limits:
    # ========================================
    # Container Limits
    # ========================================
    - type: Container
      # Maximum resources a single container can request
      # Note: Redis Enterprise Operator nodes can request up to 2 CPU, 4Gi
      # Set max slightly higher to allow flexibility
      max:
        cpu: "4"        # Allow up to 4 CPUs per container
        memory: "8Gi"   # Allow up to 8Gi per container

      # Minimum resources a container must request
      min:
        cpu: "100m"
        memory: "128Mi"

      # Default limits (if not specified in pod spec)
      # These apply to sidecar containers, monitoring, etc.
      default:
        cpu: "500m"
        memory: "1Gi"

      # Default requests (if not specified in pod spec)
      defaultRequest:
        cpu: "250m"
        memory: "512Mi"

    # ========================================
    # Pod Limits
    # ========================================
    - type: Pod
      # Maximum resources across all containers in a pod
      # Redis Enterprise pods can have multiple containers (redis + sidecars)
      max:
        cpu: "6"        # Allow headroom for main + sidecar containers
        memory: "12Gi"  # Allow headroom for main + sidecar containers
    
    # ========================================
    # PersistentVolumeClaim Limits
    # ========================================
    - type: PersistentVolumeClaim
      min:
        storage: "1Gi"
      max:
        storage: "20Gi"

# ========================================
# How to Apply
# ========================================
# For redis-orders-dev:
#   oc apply -f platform/quotas/dev-limitrange-template.yaml -n redis-orders-dev
#
# Verify:
#   oc get limitrange -n redis-orders-dev
#   oc describe limitrange redis-dev-limits -n redis-orders-dev
#
# ========================================
# What This Does
# ========================================
# 1. If a pod doesn't specify resources, it gets defaults (250m CPU, 512Mi RAM)
# 2. No container can request more than 2 CPU or 4Gi RAM
# 3. No pod can request more than 4 CPU or 8Gi RAM total
# 4. PVCs must be between 1Gi and 20Gi

