---
# LimitRange for Production Namespaces
# Purpose: Set default and maximum resource limits for containers (higher than dev)
# Managed by: Platform Team
# Applied to: redis-*-prod namespaces

apiVersion: v1
kind: LimitRange
metadata:
  name: redis-prod-limits
  labels:
    environment: prod
    managed-by: platform-team
    resource-type: limitrange
spec:
  limits:
    # ========================================
    # Container Limits (Higher than dev for production workloads)
    # ========================================
    - type: Container
      # Maximum resources a single container can request
      # Note: Production Redis Enterprise nodes may need more resources
      max:
        cpu: "8"        # Allow up to 8 CPUs per container (production workloads)
        memory: "16Gi"  # Allow up to 16Gi per container
      min:
        cpu: "100m"
        memory: "128Mi"
      default:
        cpu: "1"
        memory: "2Gi"
      defaultRequest:
        cpu: "500m"
        memory: "1Gi"

    # ========================================
    # Pod Limits (Higher than dev for production workloads)
    # ========================================
    - type: Pod
      # Maximum resources across all containers in a pod
      max:
        cpu: "12"       # Allow headroom for main + sidecar containers
        memory: "24Gi"  # Allow headroom for main + sidecar containers
    
    # ========================================
    # PersistentVolumeClaim Limits (5x dev limits)
    # ========================================
    - type: PersistentVolumeClaim
      min:
        storage: "1Gi"
      max:
        storage: "100Gi"

# ========================================
# How to Apply
# ========================================
# For redis-orders-prod:
#   oc apply -f platform/quotas/prod-limitrange-template.yaml -n redis-orders-prod

