---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gatekeeper-policies
  namespace: openshift-gitops
  labels:
    app: gatekeeper-policies
    managed-by: platform-team
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform-team
  
  source:
    repoURL: https://github.com/alan-teodoro/poc-gitops.git
    targetRevision: main
    path: platform/policies
    directory:
      recurse: true
  
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gatekeeper-system
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  
  # Health assessment
  ignoreDifferences:
    - group: templates.gatekeeper.sh
      kind: ConstraintTemplate
      jsonPointers:
        - /status

