---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-namespaces
  namespace: openshift-gitops
  labels:
    app: redis-namespaces
    managed-by: platform-team
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform-team
  
  source:
    repoURL: https://github.com/alan-teodoro/poc-gitops.git
    targetRevision: main
    path: clusters/redis-cluster-demo/namespaces
    directory:
      recurse: false
  
  destination:
    server: https://kubernetes.default.svc
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

